# Generated by Django 5.0.3 on 2024-09-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
