# Generated by Django 3.2.12 on 2024-09-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todo_list',
            new_name='todo_task',
        ),
    ]
